api:
  dashboard: true
  debug: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: n8n-net

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@intelligencebox.it
      storage: /data/acme.json
      httpChallenge:
        entryPoint: http